// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "sebastian.capotondo@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "This method is useful to make a healthcheck",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healdh"
                ],
                "summary": "Healthcheck for microservice",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/notification/:type": {
            "post": {
                "description": "This method is useful to send an email\nRestrictions:\n- Status type: not more than 2 per minute for each recipient\n- News type: not more than 1 per day for each recipient\n- Marketing type: not more than 1 per day for each recipient",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notification"
                ],
                "summary": "Sends a notification",
                "parameters": [
                    {
                        "type": "string",
                        "example": "some message",
                        "name": "message",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "news",
                            "status",
                            "marketing"
                        ],
                        "type": "string",
                        "example": "news",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "user-1",
                        "name": "user",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "429": {
                        "description": "Too many requests"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Golang Rate Limit API",
	Description:      "Golang Rate Limit API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
